# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table book (
  isbn                          integer generated by default as identity (start with 1)  not null,
  title                         varchar(255),
  sector                        varchar(255),
  publication_date              date,
  publisher                     varchar(255),
  no_of_pages                   integer not null,
  constraint pk_book primary key (isbn)
);

create table author (
  book_isbn                     integer not null,
  author                        varchar(255) not null
);

create table borrow_book (
  borrow_id                     integer generated by default as identity (start with 1)  not null,
  book_isbn                     integer not null,
  reader_id                     integer,
  borrowed_day                  integer default 0 not null,
  borrowed_month                integer default 0 not null,
  borrowed_year                 integer default 0 not null,
  borrowed_minute               integer default 0 not null,
  borrowed_hour                 integer default 0 not null,
  returned_day                  integer default 0 not null,
  returned_month                integer default 0 not null,
  returned_year                 integer default 0 not null,
  returned_minute               integer default 0 not null,
  returned_hour                 integer default 0 not null,
  constraint pk_borrow_book primary key (borrow_id)
);

create table borrow_dvd (
  borrow_id                     integer generated by default as identity (start with 1)  not null,
  dvd_isbn                      integer not null,
  reader_id                     integer,
  borrowed_day                  integer default 0 not null,
  borrowed_month                integer default 0 not null,
  borrowed_year                 integer default 0 not null,
  borrowed_minute               integer default 0 not null,
  borrowed_hour                 integer default 0 not null,
  returned_day                  integer default 0 not null,
  returned_month                integer default 0 not null,
  returned_year                 integer default 0 not null,
  returned_minute               integer default 0 not null,
  returned_hour                 integer default 0 not null,
  constraint pk_borrow_dvd primary key (borrow_id)
);

create table dvd (
  isbn                          integer generated by default as identity (start with 1)  not null,
  title                         varchar(255),
  sector                        varchar(255),
  publication_date              date,
  language                      varchar(255),
  producer                      varchar(255),
  constraint pk_dvd primary key (isbn)
);

create table subtitle (
  dvd_isbn                      integer not null,
  subtitle                      varchar(255) not null
);

create table actor (
  dvd_isbn                      integer not null,
  actor                         varchar(255) not null
);

create table reader (
  id                            integer generated by default as identity (start with 1)  not null,
  name                          varchar(255),
  mob_number                    integer not null,
  email                         varchar(255),
  constraint pk_reader primary key (id)
);

create table reserve_book (
  reserve_id                    integer generated by default as identity (start with 1)  not null,
  book_isbn                     integer not null,
  reader_id                     integer,
  reserve_day                   integer default 0 not null,
  reserve_month                 integer default 0 not null,
  reserve_year                  integer default 0 not null,
  reserve_minute                integer default 0 not null,
  reserve_hour                  integer default 0 not null,
  constraint pk_reserve_book primary key (reserve_id)
);

create table reserve_dvd (
  reserve_id                    integer generated by default as identity (start with 1)  not null,
  dvd_isbn                      integer not null,
  reader_id                     integer,
  reserve_day                   integer default 0 not null,
  reserve_month                 integer default 0 not null,
  reserve_year                  integer default 0 not null,
  reserve_minute                integer default 0 not null,
  reserve_hour                  integer default 0 not null,
  constraint pk_reserve_dvd primary key (reserve_id)
);

create index ix_author_book_isbn on author (book_isbn);
alter table author add constraint fk_author_book_isbn foreign key (book_isbn) references book (isbn) on delete restrict on update restrict;

create index ix_author_book on author (book_isbn);
alter table author add constraint fk_author_book foreign key (book_isbn) references book (isbn) on delete restrict on update restrict;

create index ix_borrow_book_book_isbn on borrow_book (book_isbn);
alter table borrow_book add constraint fk_borrow_book_book_isbn foreign key (book_isbn) references book (isbn) on delete restrict on update restrict;

create index ix_borrow_book_reader_id on borrow_book (reader_id);
alter table borrow_book add constraint fk_borrow_book_reader_id foreign key (reader_id) references reader (id) on delete restrict on update restrict;

create index ix_borrow_dvd_dvd_isbn on borrow_dvd (dvd_isbn);
alter table borrow_dvd add constraint fk_borrow_dvd_dvd_isbn foreign key (dvd_isbn) references dvd (isbn) on delete restrict on update restrict;

create index ix_borrow_dvd_reader_id on borrow_dvd (reader_id);
alter table borrow_dvd add constraint fk_borrow_dvd_reader_id foreign key (reader_id) references reader (id) on delete restrict on update restrict;

create index ix_subtitle_dvd_isbn on subtitle (dvd_isbn);
alter table subtitle add constraint fk_subtitle_dvd_isbn foreign key (dvd_isbn) references dvd (isbn) on delete restrict on update restrict;

create index ix_subtitle_dvd on subtitle (dvd_isbn);
alter table subtitle add constraint fk_subtitle_dvd foreign key (dvd_isbn) references dvd (isbn) on delete restrict on update restrict;

create index ix_actor_dvd_isbn on actor (dvd_isbn);
alter table actor add constraint fk_actor_dvd_isbn foreign key (dvd_isbn) references dvd (isbn) on delete restrict on update restrict;

create index ix_actor_dvd on actor (dvd_isbn);
alter table actor add constraint fk_actor_dvd foreign key (dvd_isbn) references dvd (isbn) on delete restrict on update restrict;

create index ix_reserve_book_book_isbn on reserve_book (book_isbn);
alter table reserve_book add constraint fk_reserve_book_book_isbn foreign key (book_isbn) references book (isbn) on delete restrict on update restrict;

create index ix_reserve_book_reader_id on reserve_book (reader_id);
alter table reserve_book add constraint fk_reserve_book_reader_id foreign key (reader_id) references reader (id) on delete restrict on update restrict;

create index ix_reserve_dvd_dvd_isbn on reserve_dvd (dvd_isbn);
alter table reserve_dvd add constraint fk_reserve_dvd_dvd_isbn foreign key (dvd_isbn) references dvd (isbn) on delete restrict on update restrict;

create index ix_reserve_dvd_reader_id on reserve_dvd (reader_id);
alter table reserve_dvd add constraint fk_reserve_dvd_reader_id foreign key (reader_id) references reader (id) on delete restrict on update restrict;


# --- !Downs

alter table author drop constraint if exists fk_author_book_isbn;
drop index if exists ix_author_book_isbn;

alter table author drop constraint if exists fk_author_book;
drop index if exists ix_author_book;

alter table borrow_book drop constraint if exists fk_borrow_book_book_isbn;
drop index if exists ix_borrow_book_book_isbn;

alter table borrow_book drop constraint if exists fk_borrow_book_reader_id;
drop index if exists ix_borrow_book_reader_id;

alter table borrow_dvd drop constraint if exists fk_borrow_dvd_dvd_isbn;
drop index if exists ix_borrow_dvd_dvd_isbn;

alter table borrow_dvd drop constraint if exists fk_borrow_dvd_reader_id;
drop index if exists ix_borrow_dvd_reader_id;

alter table subtitle drop constraint if exists fk_subtitle_dvd_isbn;
drop index if exists ix_subtitle_dvd_isbn;

alter table subtitle drop constraint if exists fk_subtitle_dvd;
drop index if exists ix_subtitle_dvd;

alter table actor drop constraint if exists fk_actor_dvd_isbn;
drop index if exists ix_actor_dvd_isbn;

alter table actor drop constraint if exists fk_actor_dvd;
drop index if exists ix_actor_dvd;

alter table reserve_book drop constraint if exists fk_reserve_book_book_isbn;
drop index if exists ix_reserve_book_book_isbn;

alter table reserve_book drop constraint if exists fk_reserve_book_reader_id;
drop index if exists ix_reserve_book_reader_id;

alter table reserve_dvd drop constraint if exists fk_reserve_dvd_dvd_isbn;
drop index if exists ix_reserve_dvd_dvd_isbn;

alter table reserve_dvd drop constraint if exists fk_reserve_dvd_reader_id;
drop index if exists ix_reserve_dvd_reader_id;

drop table if exists book;

drop table if exists author;

drop table if exists borrow_book;

drop table if exists borrow_dvd;

drop table if exists dvd;

drop table if exists subtitle;

drop table if exists actor;

drop table if exists reader;

drop table if exists reserve_book;

drop table if exists reserve_dvd;

